***
tensorflow 코드 모음입니다.
***

# 새로운 축 추가하기

In [1]:
import tensorflow as tf
import numpy as np

In [7]:
x = np.random.rand(4,2,2)
print(x)
print(x.shape)

[[[0.93047955 0.81575441]
  [0.54309143 0.31435391]]

 [[0.79096763 0.24945972]
  [0.33245036 0.14846471]]

 [[0.67329039 0.85104668]
  [0.10029469 0.84271959]]

 [[0.50068417 0.76320642]
  [0.04881908 0.7371354 ]]]
(4, 2, 2)


In [8]:
newx1 = x[tf.newaxis,...]
print(newx1.shape)

(1, 4, 2, 2)


In [10]:
newx2 = x[..., tf.newaxis]
print(newx2.shape)

(4, 2, 2, 1)


인덱싱에서 ellipsis(...)는 여러개 사용 못함

In [11]:
newx3 = x[..., tf.newaxis, ...]

IndexError: an index can only have a single ellipsis ('...')

# tf.cast()

tf.cast(x, dtype, name=None)

기존 tensor를 새로운 타입으로 변경할 때 사용 가능

# tf.math.logical_not()

False인 부분을 True로 바꿔줌 (boolen타입이라면)

In [2]:
boolen = tf.constant([True, False], dtype=tf.bool)
tf.math.logical_not(boolen)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

활용할 수 있는 부분 ==> mask할 때 필요.
