***
tensorflow 코드 모음입니다.
***

# 새로운 축 추가하기

In [1]:
import tensorflow as tf
import numpy as np

In [7]:
x = np.random.rand(4,2,2)
print(x)
print(x.shape)

[[[0.93047955 0.81575441]
  [0.54309143 0.31435391]]

 [[0.79096763 0.24945972]
  [0.33245036 0.14846471]]

 [[0.67329039 0.85104668]
  [0.10029469 0.84271959]]

 [[0.50068417 0.76320642]
  [0.04881908 0.7371354 ]]]
(4, 2, 2)


In [8]:
newx1 = x[tf.newaxis,...]
print(newx1.shape)

(1, 4, 2, 2)


In [10]:
newx2 = x[..., tf.newaxis]
print(newx2.shape)

(4, 2, 2, 1)


인덱싱에서 ellipsis(...)는 여러개 사용 못함

In [11]:
newx3 = x[..., tf.newaxis, ...]

IndexError: an index can only have a single ellipsis ('...')

# tf.cast()

tf.cast(x, dtype, name=None)

기존 tensor를 새로운 타입으로 변경할 때 사용 가능

# tf.math.logical_not()

False인 부분을 True로 바꿔줌 (boolen타입이라면)

In [2]:
boolen = tf.constant([True, False], dtype=tf.bool)
tf.math.logical_not(boolen)

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([False,  True])>

활용할 수 있는 부분 ==> mask할 때 필요.


# tf.gather_nd(params, slices)

params 어레이를 indices 어레이의 인덱스를 가지고 슬라이를 하는 것임 

In [27]:
indices = np.array([[0,0], [1,1]])
params = np.array([['a', 'b'], ['c', 'd']])

In [28]:
output = tf.gather_nd(params, indices)
output.numpy()

array([b'a', b'd'], dtype=object)

indices의 첫번째 요소가 (0,0)이기 때문에, params에서 0번째 row의 0번째 column을 선택하고, 두번째요소가 (1,1)이기 때문에 params에서 1번째 row의 1번째 column을 선택함.

ouput의 크기는 (2,)가 됨

In [14]:
indices = np.array([[1], [0]])
params = np.array([['a', 'b'], ['c', 'd']])

In [15]:
output = tf.gather_nd(params, indices)
output.numpy()

array([[b'c', b'd'],
       [b'a', b'b']], dtype=object)

indices의 첫번째 요소가 [1]이기 때문에, params의 두번째 row전체를 선택하고, 두번째 요소가 [0] 이기 때문에 params의 첫번째 row전체를 선택함

output의 크기는 (2,2)가 됨

In [20]:
indices = np.array([[1]])
params = np.array([[['a0', 'b0'], ['c0', 'd0']],
                   [['a1', 'b1'], ['c1', 'd1']]])

In [22]:
output = tf.gather_nd(params, indices)
output.numpy()

array([[[b'a1', b'b1'],
        [b'c1', b'd1']]], dtype=object)

indices의 첫번째 요소가 [1]만 있기 때문에, params에서 2번째 row를 전체 선택함. 

사이즈는 params이 3차원 dimension이기 때문에, output크기는 (1,2,2)가 됨

In [30]:
indices = np.array([[0, 1], [1, 0]])
params = np.array([[['a0', 'b0'], ['c0', 'd0']],
                  [['a1', 'b1'], ['c1', 'd1']]])

In [32]:
output = tf.gather_nd(params, indices)
output.numpy()

array([[b'c0', b'd0'],
       [b'a1', b'b1']], dtype=object)

In [33]:
indices = np.array([[0, 0, 1], [1, 0, 1]])
params = np.array([[['a0', 'b0'], ['c0', 'd0']],
                  [['a1', 'b1'], ['c1', 'd1']]])

In [34]:
output = tf.gather_nd(params, indices)
output.numpy()

array([b'b0', b'b1'], dtype=object)